import { imagePathFinder } from "@/utils/imagePathFinder";
import type { Metadata } from "next";
import Image from "next/image";
import Link from "next/link";


export const metadata: Metadata = {
    title: "Industrielle RH",
    description: "Generated by create next app",
};

export default function AuthLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <section className="flex flex-col items-center justify-center bg-gray-100 w-full h-[100vh] overflow-x-hidden max-w-full p-0 m-0">
            <div className="flex h-full w-full  items-center justify-center">
                <div className="w-1/2 flex items-center justify-center">
                    <Link href="/" className="absolute left-10 top-10">
                        <Image src={imagePathFinder.logo} alt="logo" width={150} />
                    </Link>
                    <main className="m-auto">
                        {children}
                    </main>
                </div>
                <div className="bg-[url(/images/login.png)] bg-cover bg-center w-1/2 h-full">
                </div>
            </div>
        </section>
    );
}
