import type { Metadata } from "next";
import { Plus_Jakarta_Sans } from "next/font/google";
import "../css/globals.css";
import { Navbar } from "@/components/navbar";
import { Footer } from "@/components/footer";

const plus_Jakarta_Sans = Plus_Jakarta_Sans({
  variable: "--font-Plus-Jakarta-Sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fr" >
      <body
        className={`${plus_Jakarta_Sans.className} antialiased`}
        style={{ maxWidth: "100vw", width: "100vw", overflowX: "hidden", backgroundColor : "#fff" }}
      >
        <Navbar/>
        {children}
        <Footer/>
      </body>
    </html>
  );
}
