import type { Metadata } from "next";

import "../css/globals.css";
import { Plus_Jakarta_Sans } from "next/font/google";
import { LanguageProvider } from "@/contexts/LanguageContext";
import { ComplianceProvider } from "./(views)/valid-cnesst/context/ComplianceContext";


const plus_Jakarta_Sans = Plus_Jakarta_Sans({
  variable: "--font-Plus-Jakarta-Sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fr" >
          <body className={`${plus_Jakarta_Sans.className} antialiased text-black`} style={{
            maxWidth: "100vw",
            width: "100vw",
            overflowX: "hidden",
            backgroundColor: "#fff"
          }}>
            <LanguageProvider>
              {children}
            </LanguageProvider>
          </body>
    </html>
  );
}
