import ClientShell from "./ClientShell"; // 👇 un composant client

export const metadata = {
  title: "Industrielle RH",
  description: "Generated by create next app",
};

export default function Layout({ children }: { children: React.ReactNode }) {
  return <ClientShell>{children}</ClientShell>;
}
