import type { Metadata } from "next";

import { Navbar } from "@/components/navbar";
import { Footer } from "@/components/footer";



export const metadata: Metadata = {
  title: "Industrielle RH",
  description: "Generated by create next app",
};

export default function ViewsLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <Navbar />
      <main className="flex flex-col items-center justify-center bg-gray-100 w-full overflow-x-hidden max-w-full pt-16">
        {children}
      </main>
      <Footer />
    </>
  );
}
